### ISSUE TITLE
Parallel Program Request

### ISSUE THREAD

**Issue by Girafe99** [solelychloe/solely.codes#1]
I have the Parallel Program emblem and I would like to get added to the Parallel Program List.

Bungie Name:

**Comment by UdayUG90** [comment]
uday ug#4134

**Comment by solelychloe** [comment]
> I have the Parallel Program emblem and I would like to get added to the Parallel Program List.
> 
> Bungie Name:

Hi @Girafe99. I do not see the Parallel Program emblem in your Collections tab, unfortunately. But once you do, I can proceed by adding you.

Have a nice day!


@UdayUG90 you have your Bungie.net profile data set to private, so I cannot see if you have the emblem or not.

**Comment by UdayUG90** [comment]
Sorry 😔 now you can check my settings are changed sorry for trouble

**Comment by UdayUG90** [comment]
uday ug#4134
